trigger: none

parameters:
  - name: runSetup
    displayName: 'Run Setup Job?'
    type: boolean
    default: true

  - name: runInit
    displayName: 'Run Terraform Init?'
    type: boolean
    default: false

  - name: runValidate
    displayName: 'Run Terraform Validate?'
    type: boolean
    default: false

  - name: runPlan
    displayName: 'Run Terraform Plan?'
    type: boolean
    default: false

  - name: runApply
    displayName: 'Run Terraform Apply?'
    type: boolean
    default: false

variables:
  - group: TerraformSecrets

jobs:
- job: Setup
  displayName: 'Setup Environment'
  condition: eq('${{ parameters.runSetup }}', true)
  pool:
    name: agent-pool-devops
  steps:
    - task: PowerShell@2
      displayName: 'Print Hello World'
      inputs:
        targetType: 'inline'
        script: 'Write-Host "Hello World"'

    - task: TerraformInstaller@1
      displayName: 'Install Terraform CLI'
      inputs:
        terraformVersion: 'latest'

- job: TerraformJob
  displayName: 'Run Selected Terraform Actions'
  pool:
    name: agent-pool-devops
  steps:
    - ${{ if eq(parameters.runInit, true) }}:
      - task: TerraformTask@5
        displayName: 'Terraform Init'
        inputs:
          provider: 'azurerm'
          command: 'init'
          backendServiceArm: 'terraform-manual-conn-new'
          backendAzureRmStorageAccountName: 'teststaccountdhondhu'
          backendAzureRmContainerName: 'testcontainer'
          backendAzureRmKey: 'terraform.tfstate'
        env:
          ARM_CLIENT_ID: '$(ARM_CLIENT_ID)'
          ARM_CLIENT_SECRET: '$(ARM_CLIENT_SECRET)'
          ARM_TENANT_ID: '$(ARM_TENANT_ID)'
          ARM_SUBSCRIPTION_ID: '$(ARM_SUBSCRIPTION_ID)'

    - ${{ if eq(parameters.runValidate, true) }}:
      - task: TerraformTask@5
        displayName: 'Terraform Validate'
        inputs:
          provider: 'azurerm'
          command: 'validate'

    - ${{ if eq(parameters.runPlan, true) }}:
      - task: TerraformTask@5
        displayName: 'Terraform Plan'
        inputs:
          provider: 'azurerm'
          command: 'plan'
          backendServiceArm: 'terraform-manual-conn-new'
          environmentServiceNameAzureRM: 'terraform-manual-conn-new'
        env:
          ARM_CLIENT_ID: '$(ARM_CLIENT_ID)'
          ARM_CLIENT_SECRET: '$(ARM_CLIENT_SECRET)'
          ARM_TENANT_ID: '$(ARM_TENANT_ID)'
          ARM_SUBSCRIPTION_ID: '$(ARM_SUBSCRIPTION_ID)'

    - ${{ if eq(parameters.runApply, true) }}:
      - task: TerraformTask@5
        displayName: 'Terraform Apply'
        inputs:
          provider: 'azurerm'
          command: 'apply'
          backendServiceArm: 'terraform-manual-conn-new'
          environmentServiceNameAzureRM: 'terraform-manual-conn-new'
        env:
          ARM_CLIENT_ID: '$(ARM_CLIENT_ID)'
          ARM_CLIENT_SECRET: '$(ARM_CLIENT_SECRET)'
          ARM_TENANT_ID: '$(ARM_TENANT_ID)'
          ARM_SUBSCRIPTION_ID: '$(ARM_SUBSCRIPTION_ID)'
