pool: agent-pool-devops
trigger: none
steps: 
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'Write-Host "Hello World"'

- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendAzureRmStorageAccountName: 'teststaccountdhondhu'
    backendAzureRmContainerName: 'testcontainer'
    backendAzureRmKey: 'rg-/terraform.tfstate'

- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'plan'