pool: agent-pool-devops
trigger: none

# 👇 Link your variable group if you're using one
variables:
  - group: TerraformSecrets  # Optional if variables are added directly in pipeline UI

steps:
- task: PowerShell@2
  displayName: 'Print Hello World'
  inputs:
    targetType: 'inline'
    script: 'Write-Host "Hello World"'

- task: TerraformInstaller@1
  displayName: 'Install Terraform CLI'
  inputs:
    terraformVersion: 'latest'

- task: TerraformTask@5
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'terraform-manual-conn-new'
    backendAzureRmStorageAccountName: 'teststaccountdhondhu'
    backendAzureRmContainerName: 'testcontainer'
    backendAzureRmKey: 'terraform.tfstate'
  env:
    ARM_CLIENT_ID: '$(ARM_CLIENT_ID)'
    ARM_CLIENT_SECRET: '$(ARM_CLIENT_SECRET)'
    ARM_TENANT_ID: '$(ARM_TENANT_ID)'
    ARM_SUBSCRIPTION_ID: '$(ARM_SUBSCRIPTION_ID)'

- task: TerraformTask@5
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'validate'

- task: TerraformTask@5
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    backendServiceArm: 'terraform-manual-conn-new'
    environmentServiceNameAzureRM: 'terraform-manual-conn-new'
  env:
    ARM_CLIENT_ID: '$(ARM_CLIENT_ID)'
    ARM_CLIENT_SECRET: '$(ARM_CLIENT_SECRET)'
    ARM_TENANT_ID: '$(ARM_TENANT_ID)'
    ARM_SUBSCRIPTION_ID: '$(ARM_SUBSCRIPTION_ID)'

- task: TerraformTask@5
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    backendServiceArm: 'terraform-manual-conn-new'
    environmentServiceNameAzureRM: 'terraform-manual-conn-new'
  env:
    ARM_CLIENT_ID: '$(ARM_CLIENT_ID)'
    ARM_CLIENT_SECRET: '$(ARM_CLIENT_SECRET)'
    ARM_TENANT_ID: '$(ARM_TENANT_ID)'
    ARM_SUBSCRIPTION_ID: '$(ARM_SUBSCRIPTION_ID)'
